plugins {
    id 'application'
    id 'org.jetbrains.kotlin.jvm' version '2.0.20'
}

repositories {
    mavenCentral()
    mavenLocal()
    test {
        useJUnitPlatform()
    }
    flatDir {
        dirs 'libs'
    }
}

def jerseyVersion = '3.0.3'
def kotlinVersion = '2.0.20'
def kotlinTestVersion = '1.6.0'
def grizzlyVersion = '3.1.1'

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlinVersion"
    testImplementation "org.jetbrains.kotlin:kotlin-test:$kotlinTestVersion"
    testImplementation "org.jetbrains.kotlin:kotlin-test-junit:$kotlinTestVersion"
    //JERSEY
    implementation "org.glassfish.jersey.containers:jersey-container-grizzly2-http:$grizzlyVersion"
    implementation "org.glassfish.jersey.inject:jersey-hk2:$jerseyVersion"
    implementation "org.glassfish.jersey.media:jersey-media-json-jackson:$jerseyVersion"
    //JERSEY_EOD
    //AWS
    implementation 'com.amazonaws:aws-lambda-java-core:1.2.3'
    implementation 'com.amazonaws:aws-lambda-java-events:3.14.0'
    runtimeOnly 'com.amazonaws:aws-lambda-java-log4j2:1.6.0'
    //AWS_EOD
    implementation "org.jetbrains.kotlin:kotlin-reflect:$kotlinVersion"
    implementation "jakarta.servlet:jakarta.servlet-api:5.0.0"
}

task copyDependencies(type: Copy) {
    into("$buildDir/libs")
    from(configurations.runtimeClasspath) {
        into 'lib'
    }
}

tasks.register('koupper-executor', Jar) {
    group = 'build'
    archiveBaseName.set('koupper-executor') // Nombre del JAR
    destinationDirectory.set(file("${buildDir}/libs")) // Directorio de salida

    // Incluye tus clases compiladas
    from(sourceSets.main.output) {
        // Incluir clases específicas
        include 'dev/koupper/controllers/AWSLambdaController.class'   // AWSLambdaController
        include 'dev/koupper/extensions/helloWorld.class'             // helloWorld desde extensions
        include 'server/handlers/RequestHandlerGetGreeting.class'     // RequestHandler de server.handlers

        // Si hay clases con sufijo Kt que deben incluirse, por ejemplo:
        include 'dev/koupper/controllers/AWSLambdaControllerKt.class'   // Si AWSLambdaController es un archivo Kotlin
        include 'dev/koupper/extensions/HelloWorldKt.class'             // Si helloWorld está en un archivo Kotlin
        include 'server/handlers/RequestHandlerGetGreetingKt.class'     // Si RequestHandler es un archivo Kotlin
    }


    // Incluye las dependencias externas
    from({
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    })

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    doLast {
        println "Fat JAR generated successfully: ${archiveFile.get().asFile}"
    }
}

application {
    mainClass.set("server.handlers.RequestHandlerGetGreetingKt")
}

startScripts.dependsOn(copyDependencies)

version = '1.0.0'
